services:
  backend:
    build: ./backend
    ports: ["8000:8000"]
    volumes:
      - ./backend/outputs:/app/outputs
    # Enable the following to use an NVIDIA GPU (requires nvidia-container-toolkit)
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - HF_HOME=/app/.cache/huggingface

  frontend:
    build: ./frontend
    ports: ["3000:3000"]
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
